version: "3"

services:

    apache:
        build: docker/apache/
        ports: [ 80 ]
        volumes:
            - ".:/var/www/html"
        networks:
            - backend
            - frontend
        depends_on:
            - php

    php:
        build: docker/php/
        volumes:
            - ".:/var/www/html"
        networks:
            - backend
        command: bash -c "composer install && php-fpm"

networks:
    backend: ~
    frontend: ~
